require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventAttendancesController do

  # This should return the minimal set of attributes required to create a valid
  # EventAttendance. As you add validations to EventAttendance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventAttendancesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  before :each do
    controller.stub!(:require_login).and_return(:true)
  end

  describe "GET index" do
    it "assigns all event_attendances as @event_attendances" do
      event_attendance = EventAttendance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:event_attendances).should eq([event_attendance])
    end
  end

  describe "GET show" do
    it "assigns the requested event_attendance as @event_attendance" do
      event_attendance = EventAttendance.create! valid_attributes
      get :show, {:id => event_attendance.to_param}, valid_session
      assigns(:event_attendance).should eq(event_attendance)
    end
  end

  describe "GET new" do
    it "assigns a new event_attendance as @event_attendance" do
      get :new, {}, valid_session
      assigns(:event_attendance).should be_a_new(EventAttendance)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_attendance as @event_attendance" do
      event_attendance = EventAttendance.create! valid_attributes
      get :edit, {:id => event_attendance.to_param}, valid_session
      assigns(:event_attendance).should eq(event_attendance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventAttendance" do
        expect {
          post :create, {:event_attendance => valid_attributes}, valid_session
        }.to change(EventAttendance, :count).by(1)
      end

      it "assigns a newly created event_attendance as @event_attendance" do
        post :create, {:event_attendance => valid_attributes}, valid_session
        assigns(:event_attendance).should be_a(EventAttendance)
        assigns(:event_attendance).should be_persisted
      end

      it "redirects to the created event_attendance" do
        post :create, {:event_attendance => valid_attributes}, valid_session
        response.should redirect_to(EventAttendance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_attendance as @event_attendance" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventAttendance.any_instance.stub(:save).and_return(false)
        post :create, {:event_attendance => {}}, valid_session
        assigns(:event_attendance).should be_a_new(EventAttendance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventAttendance.any_instance.stub(:save).and_return(false)
        post :create, {:event_attendance => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event_attendance" do
        event_attendance = EventAttendance.create! valid_attributes
        # Assuming there are no other event_attendances in the database, this
        # specifies that the EventAttendance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventAttendance.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => event_attendance.to_param, :event_attendance => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested event_attendance as @event_attendance" do
        event_attendance = EventAttendance.create! valid_attributes
        put :update, {:id => event_attendance.to_param, :event_attendance => valid_attributes}, valid_session
        assigns(:event_attendance).should eq(event_attendance)
      end

      it "redirects to the event_attendance" do
        event_attendance = EventAttendance.create! valid_attributes
        put :update, {:id => event_attendance.to_param, :event_attendance => valid_attributes}, valid_session
        response.should redirect_to(event_attendance)
      end
    end

    describe "with invalid params" do
      it "assigns the event_attendance as @event_attendance" do
        event_attendance = EventAttendance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventAttendance.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_attendance.to_param, :event_attendance => {}}, valid_session
        assigns(:event_attendance).should eq(event_attendance)
      end

      it "re-renders the 'edit' template" do
        event_attendance = EventAttendance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventAttendance.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_attendance.to_param, :event_attendance => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_attendance" do
      event_attendance = EventAttendance.create! valid_attributes
      expect {
        delete :destroy, {:id => event_attendance.to_param}, valid_session
      }.to change(EventAttendance, :count).by(-1)
    end

    it "redirects to the event_attendances list" do
      event_attendance = EventAttendance.create! valid_attributes
      delete :destroy, {:id => event_attendance.to_param}, valid_session
      response.should redirect_to(event_attendances_url)
    end
  end

end
