require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventOccurrencesController do

  # This should return the minimal set of attributes required to create a valid
  # EventOccurrence. As you add validations to EventOccurrence, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventOccurrencesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  before :each do
    controller.stub!(:require_login).and_return(:true)
    controller.stub!(:leader?).and_return(:true)
    controller.stub!(:admin?).and_return(:true)
  end

  describe "GET index" do
    it "assigns all event_occurrences as @event_occurrences" do
      event_occurrence = FactoryGirl.create(:event_occurrence)
      get :index, {}, valid_session
      assigns(:event_occurrences).should eq([event_occurrence])
    end
  end

  describe "GET show" do
    it "assigns the requested event_occurrence as @event_occurrence" do
      event_occurrence = FactoryGirl.create(:event_occurrence)
      get :show, {:id => event_occurrence.to_param}, valid_session
      assigns(:event_occurrence).should eq(event_occurrence)
    end
  end

  describe "GET new" do
    it "assigns a new event_occurrence as @event_occurrence" do
      get :new, {}, valid_session
      assigns(:event_occurrence).should be_a_new(EventOccurrence)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_occurrence as @event_occurrence" do
      event_occurrence = FactoryGirl.create(:event_occurrence)
      get :edit, {:id => event_occurrence.to_param}, valid_session
      assigns(:event_occurrence).should eq(event_occurrence)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventOccurrence" do
        EventOccurrence.any_instance.should_receive(:save).and_return(true)
        post :create, {:event_occurrence => valid_attributes}, valid_session
      end

      it "assigns a newly created event_occurrence as @event_occurrence" do
        EventOccurrence.any_instance.should_receive(:save).and_return(true)
        post :create, {:event_occurrence => valid_attributes}, valid_session
        assigns(:event_occurrence).should be_a(EventOccurrence)
      end

      it "redirects to the created event_occurrence" do
        EventOccurrence.any_instance.should_receive(:save).and_return(true)
        post :create, {:event_occurrence => valid_attributes}, valid_session
        response.should redirect_to(EventOccurrence.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_occurrence as @event_occurrence" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventOccurrence.any_instance.stub(:save).and_return(false)
        post :create, {:event_occurrence => {}}, valid_session
        assigns(:event_occurrence).should be_a_new(EventOccurrence)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventOccurrence.any_instance.stub(:save).and_return(false)
        post :create, {:event_occurrence => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event_occurrence" do
        event_occurrence = FactoryGirl.create(:event_occurrence)
        # Assuming there are no other event_occurrences in the database, this
        # specifies that the EventOccurrence created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventOccurrence.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => event_occurrence.to_param, :event_occurrence => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested event_occurrence as @event_occurrence" do
        event_occurrence = FactoryGirl.create(:event_occurrence)
        put :update, {:id => event_occurrence.to_param, :event_occurrence => valid_attributes}, valid_session
        assigns(:event_occurrence).should eq(event_occurrence)
      end

      it "redirects to the event_occurrence" do
        event_occurrence = FactoryGirl.create(:event_occurrence)
        put :update, {:id => event_occurrence.to_param, :event_occurrence => valid_attributes}, valid_session
        response.should redirect_to(event_occurrence)
      end
    end

    describe "with invalid params" do
      it "assigns the event_occurrence as @event_occurrence" do
        event_occurrence = FactoryGirl.create(:event_occurrence)
        # Trigger the behavior that occurs when invalid params are submitted
        EventOccurrence.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_occurrence.to_param, :event_occurrence => {}}, valid_session
        assigns(:event_occurrence).should eq(event_occurrence)
      end

      it "re-renders the 'edit' template" do
        event_occurrence = FactoryGirl.create(:event_occurrence)
        # Trigger the behavior that occurs when invalid params are submitted
        EventOccurrence.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_occurrence.to_param, :event_occurrence => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_occurrence" do
      event_occurrence = FactoryGirl.create(:event_occurrence)
      expect {
        delete :destroy, {:id => event_occurrence.to_param}, valid_session
      }.to change(EventOccurrence, :count).by(-1)
    end

    it "redirects to the event_occurrences list" do
      event_occurrence = FactoryGirl.create(:event_occurrence)
      delete :destroy, {:id => event_occurrence.to_param}, valid_session
      response.should redirect_to(event_occurrences_url)
    end
  end

end
