require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequirementObtainmentsController do

  # This should return the minimal set of attributes required to create a valid
  # RequirementObtainment. As you add validations to RequirementObtainment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequirementObtainmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  before :each do
    controller.stub!(:require_login).and_return(:true)
    controller.stub!(:leader?).and_return(:true)
    controller.stub!(:admin?).and_return(:true)
  end

  describe "GET index" do
    it "assigns all requirement_obtainments as @requirement_obtainments" do
      requirement_obtainment = RequirementObtainment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:requirement_obtainments).should eq([requirement_obtainment])
    end
  end

  describe "GET show" do
    it "assigns the requested requirement_obtainment as @requirement_obtainment" do
      requirement_obtainment = RequirementObtainment.create! valid_attributes
      get :show, {:id => requirement_obtainment.to_param}, valid_session
      assigns(:requirement_obtainment).should eq(requirement_obtainment)
    end
  end

  describe "GET new" do
    it "assigns a new requirement_obtainment as @requirement_obtainment" do
      get :new, {}, valid_session
      assigns(:requirement_obtainment).should be_a_new(RequirementObtainment)
    end
  end

  describe "GET edit" do
    it "assigns the requested requirement_obtainment as @requirement_obtainment" do
      requirement_obtainment = RequirementObtainment.create! valid_attributes
      get :edit, {:id => requirement_obtainment.to_param}, valid_session
      assigns(:requirement_obtainment).should eq(requirement_obtainment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RequirementObtainment" do
        expect {
          post :create, {:requirement_obtainment => valid_attributes}, valid_session
        }.to change(RequirementObtainment, :count).by(1)
      end

      it "assigns a newly created requirement_obtainment as @requirement_obtainment" do
        post :create, {:requirement_obtainment => valid_attributes}, valid_session
        assigns(:requirement_obtainment).should be_a(RequirementObtainment)
        assigns(:requirement_obtainment).should be_persisted
      end

      it "redirects to the created requirement_obtainment" do
        post :create, {:requirement_obtainment => valid_attributes}, valid_session
        response.should redirect_to(RequirementObtainment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved requirement_obtainment as @requirement_obtainment" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementObtainment.any_instance.stub(:save).and_return(false)
        post :create, {:requirement_obtainment => {}}, valid_session
        assigns(:requirement_obtainment).should be_a_new(RequirementObtainment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementObtainment.any_instance.stub(:save).and_return(false)
        post :create, {:requirement_obtainment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested requirement_obtainment" do
        requirement_obtainment = RequirementObtainment.create! valid_attributes
        # Assuming there are no other requirement_obtainments in the database, this
        # specifies that the RequirementObtainment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RequirementObtainment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => requirement_obtainment.to_param, :requirement_obtainment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested requirement_obtainment as @requirement_obtainment" do
        requirement_obtainment = RequirementObtainment.create! valid_attributes
        put :update, {:id => requirement_obtainment.to_param, :requirement_obtainment => valid_attributes}, valid_session
        assigns(:requirement_obtainment).should eq(requirement_obtainment)
      end

      it "redirects to the requirement_obtainment" do
        requirement_obtainment = RequirementObtainment.create! valid_attributes
        put :update, {:id => requirement_obtainment.to_param, :requirement_obtainment => valid_attributes}, valid_session
        response.should redirect_to(requirement_obtainment)
      end
    end

    describe "with invalid params" do
      it "assigns the requirement_obtainment as @requirement_obtainment" do
        requirement_obtainment = RequirementObtainment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementObtainment.any_instance.stub(:save).and_return(false)
        put :update, {:id => requirement_obtainment.to_param, :requirement_obtainment => {}}, valid_session
        assigns(:requirement_obtainment).should eq(requirement_obtainment)
      end

      it "re-renders the 'edit' template" do
        requirement_obtainment = RequirementObtainment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequirementObtainment.any_instance.stub(:save).and_return(false)
        put :update, {:id => requirement_obtainment.to_param, :requirement_obtainment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested requirement_obtainment" do
      requirement_obtainment = RequirementObtainment.create! valid_attributes
      expect {
        delete :destroy, {:id => requirement_obtainment.to_param}, valid_session
      }.to change(RequirementObtainment, :count).by(-1)
    end

    it "redirects to the requirement_obtainments list" do
      requirement_obtainment = RequirementObtainment.create! valid_attributes
      delete :destroy, {:id => requirement_obtainment.to_param}, valid_session
      response.should redirect_to(requirement_obtainments_url)
    end
  end

end
