require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShoutsController do

  # This should return the minimal set of attributes required to create a valid
  # Shout. As you add validations to Shout, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      text: "Shout!",
      date: Time.now
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShoutsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  before :each do
    controller.stub!(:require_login).and_return(:true)
    controller.stub!(:leader?).and_return(:true)
    controller.stub!(:admin?).and_return(:true)
    controller.stub(:current_member).and_return(mock_model("Member"))
  end

  describe "GET index" do
    it "assigns all shouts as @shouts" do
      shout = FactoryGirl.create(:shout)
      get :index, {}, valid_session
      assigns(:shouts).should eq([shout])
    end
  end

  describe "GET show" do
    it "assigns the requested shout as @shout" do
      shout = FactoryGirl.create(:shout)
      get :show, {:id => shout.to_param}, valid_session
      assigns(:shout).should eq(shout)
    end
  end

  describe "GET new" do
    it "assigns a new shout as @shout" do
      get :new, {}, valid_session
      assigns(:shout).should be_a_new(Shout)
    end
  end

  describe "GET edit" do
    it "assigns the requested shout as @shout" do
      shout = FactoryGirl.create(:shout)
      get :edit, {:id => shout.to_param}, valid_session
      assigns(:shout).should eq(shout)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shout" do
        expect {
          post :create, {:shout => valid_attributes}, valid_session
        }.to change(Shout, :count).by(1)
      end

      it "assigns a newly created shout as @shout" do
        post :create, {:shout => valid_attributes}, valid_session
        assigns(:shout).should be_a(Shout)
        assigns(:shout).should be_persisted
      end

      it "redirects to the created shout" do
        post :create, {:shout => valid_attributes}, valid_session
        response.should redirect_to(Shout.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shout as @shout" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shout.any_instance.stub(:save).and_return(false)
        post :create, {:shout => {}}, valid_session
        assigns(:shout).should be_a_new(Shout)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shout.any_instance.stub(:save).and_return(false)
        post :create, {:shout => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shout" do
        shout = FactoryGirl.create(:shout)
        # Assuming there are no other shouts in the database, this
        # specifies that the Shout created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shout.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => shout.to_param, :shout => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested shout as @shout" do
        shout = FactoryGirl.create(:shout)
        put :update, {:id => shout.to_param, :shout => valid_attributes}, valid_session
        assigns(:shout).should eq(shout)
      end

      it "redirects to the shout" do
        shout = FactoryGirl.create(:shout)
        put :update, {:id => shout.to_param, :shout => valid_attributes}, valid_session
        response.should redirect_to(shout)
      end
    end

    describe "with invalid params" do
      it "assigns the shout as @shout" do
        shout = FactoryGirl.create(:shout)
        # Trigger the behavior that occurs when invalid params are submitted
        Shout.any_instance.stub(:save).and_return(false)
        put :update, {:id => shout.to_param, :shout => {}}, valid_session
        assigns(:shout).should eq(shout)
      end

      it "re-renders the 'edit' template" do
        shout = FactoryGirl.create(:shout)
        # Trigger the behavior that occurs when invalid params are submitted
        Shout.any_instance.stub(:save).and_return(false)
        put :update, {:id => shout.to_param, :shout => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shout" do
      shout = FactoryGirl.create(:shout)
      expect {
        delete :destroy, {:id => shout.to_param}, valid_session
      }.to change(Shout, :count).by(-1)
    end

    it "redirects to the shouts list" do
      shout = FactoryGirl.create(:shout)
      delete :destroy, {:id => shout.to_param}, valid_session
      response.should redirect_to(shouts_url)
    end
  end

end
